version: '3.7'

services:
  example-php-app:
    image: krizius/php:8.1-apache
    volumes:
      - .:/var/www
    networks:
      - inbound
      - persistence
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=inbound
        - traefik.http.routers.example-php-app.rule=Host(`example-php-app.localhost`)
        - traefik.http.routers.example-php-app.entrypoints=web
        - traefik.http.routers.example-php-app.service=example-php-app
        - traefik.http.services.example-php-app.loadbalancer.server.port=80
      restart_policy:
        condition: on-failure

networks:
  inbound:
    external: true
  persistence:
    external: true
